name: pos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - readline
  - tornado
  - libffi
  - debugpy
  - bzip2
  - libedit
  - zlib
  - openssl
  - libcxx
  - libsodium
  - krb5
  - zeromq
  - expat
  - sqlite
  - tk
  - lzma
  - psutil
  - pyzmq
  - ncurses
  - ipython
  - jupyterlab
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==1.26.4
      - pandas==2.3.2
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - scipy==1.16.2
      - sympy==1.14.0
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tzdata==2025.2